/*
 * The Events Calendar REST API
 * The Events Calendar REST API allows accessing upcoming events information easily and conveniently.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.soteapi.wordpress.events.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * DateDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-11T23:28:38.367+02:00")
public class DateDetails {
  @JsonProperty("year")
  private Integer year = null;

  @JsonProperty("month")
  private Integer month = null;

  @JsonProperty("day")
  private Integer day = null;

  @JsonProperty("hour")
  private Integer hour = null;

  @JsonProperty("minutes")
  private Integer minutes = null;

  @JsonProperty("seconds")
  private Integer seconds = null;

  public DateDetails year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * The date year
   * @return year
  **/
  @ApiModelProperty(value = "The date year")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public DateDetails month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * The date month
   * @return month
  **/
  @ApiModelProperty(value = "The date month")
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public DateDetails day(Integer day) {
    this.day = day;
    return this;
  }

   /**
   * The date day
   * @return day
  **/
  @ApiModelProperty(value = "The date day")
  public Integer getDay() {
    return day;
  }

  public void setDay(Integer day) {
    this.day = day;
  }

  public DateDetails hour(Integer hour) {
    this.hour = hour;
    return this;
  }

   /**
   * The date hour
   * @return hour
  **/
  @ApiModelProperty(value = "The date hour")
  public Integer getHour() {
    return hour;
  }

  public void setHour(Integer hour) {
    this.hour = hour;
  }

  public DateDetails minutes(Integer minutes) {
    this.minutes = minutes;
    return this;
  }

   /**
   * The date minutes
   * @return minutes
  **/
  @ApiModelProperty(value = "The date minutes")
  public Integer getMinutes() {
    return minutes;
  }

  public void setMinutes(Integer minutes) {
    this.minutes = minutes;
  }

  public DateDetails seconds(Integer seconds) {
    this.seconds = seconds;
    return this;
  }

   /**
   * The date seconds
   * @return seconds
  **/
  @ApiModelProperty(value = "The date seconds")
  public Integer getSeconds() {
    return seconds;
  }

  public void setSeconds(Integer seconds) {
    this.seconds = seconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DateDetails dateDetails = (DateDetails) o;
    return Objects.equals(this.year, dateDetails.year) &&
        Objects.equals(this.month, dateDetails.month) &&
        Objects.equals(this.day, dateDetails.day) &&
        Objects.equals(this.hour, dateDetails.hour) &&
        Objects.equals(this.minutes, dateDetails.minutes) &&
        Objects.equals(this.seconds, dateDetails.seconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, day, hour, minutes, seconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DateDetails {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    minutes: ").append(toIndentedString(minutes)).append("\n");
    sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

