/*
 * The Events Calendar REST API
 * The Events Calendar REST API allows accessing upcoming events information easily and conveniently.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.soteapi.wordpress.events.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ImageSize
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-11T23:28:38.367+02:00")
public class ImageSize {
  @JsonProperty("width")
  private Integer width = null;

  @JsonProperty("height")
  private Integer height = null;

  @JsonProperty("mime-type")
  private String mimeType = null;

  @JsonProperty("url")
  private String url = null;

  public ImageSize width(Integer width) {
    this.width = width;
    return this;
  }

   /**
   * The image width in pixels in the specified size
   * @return width
  **/
  @ApiModelProperty(value = "The image width in pixels in the specified size")
  public Integer getWidth() {
    return width;
  }

  public void setWidth(Integer width) {
    this.width = width;
  }

  public ImageSize height(Integer height) {
    this.height = height;
    return this;
  }

   /**
   * The image height in pixels in the specified size
   * @return height
  **/
  @ApiModelProperty(value = "The image height in pixels in the specified size")
  public Integer getHeight() {
    return height;
  }

  public void setHeight(Integer height) {
    this.height = height;
  }

  public ImageSize mimeType(String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * The image mime-type
   * @return mimeType
  **/
  @ApiModelProperty(value = "The image mime-type")
  public String getMimeType() {
    return mimeType;
  }

  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  public ImageSize url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The link to the image in the specified size on the site
   * @return url
  **/
  @ApiModelProperty(value = "The link to the image in the specified size on the site")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageSize imageSize = (ImageSize) o;
    return Objects.equals(this.width, imageSize.width) &&
        Objects.equals(this.height, imageSize.height) &&
        Objects.equals(this.mimeType, imageSize.mimeType) &&
        Objects.equals(this.url, imageSize.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(width, height, mimeType, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageSize {\n");
    
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

