/*
 * The Events Calendar REST API
 * The Events Calendar REST API allows accessing upcoming events information easily and conveniently.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.soteapi.wordpress.events.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Organizer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-11T23:28:38.367+02:00")
public class Organizer {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("global_id")
  private String globalId = null;

  @JsonProperty("global_id_lineage")
  private List<String> globalIdLineage = null;

  @JsonProperty("author")
  private Integer author = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("date_utc")
  private String dateUtc = null;

  @JsonProperty("modified")
  private String modified = null;

  @JsonProperty("modified_utc")
  private String modifiedUtc = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("organizer")
  private String organizer = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("excerpt")
  private String excerpt = null;

  @JsonProperty("image")
  private Image image = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("email")
  private String email = null;

  public Organizer id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The organizer WordPress post ID
   * @return id
  **/
  @ApiModelProperty(value = "The organizer WordPress post ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Organizer globalId(String globalId) {
    this.globalId = globalId;
    return this;
  }

   /**
   * The organizer ID used to globally identify in Event Aggregator
   * @return globalId
  **/
  @ApiModelProperty(value = "The organizer ID used to globally identify in Event Aggregator")
  public String getGlobalId() {
    return globalId;
  }

  public void setGlobalId(String globalId) {
    this.globalId = globalId;
  }

  public Organizer globalIdLineage(List<String> globalIdLineage) {
    this.globalIdLineage = globalIdLineage;
    return this;
  }

  public Organizer addGlobalIdLineageItem(String globalIdLineageItem) {
    if (this.globalIdLineage == null) {
      this.globalIdLineage = new ArrayList<String>();
    }
    this.globalIdLineage.add(globalIdLineageItem);
    return this;
  }

   /**
   * An Array containing the lineage of where this organizer comes from, this should not change after the organizer is created.
   * @return globalIdLineage
  **/
  @ApiModelProperty(value = "An Array containing the lineage of where this organizer comes from, this should not change after the organizer is created.")
  public List<String> getGlobalIdLineage() {
    return globalIdLineage;
  }

  public void setGlobalIdLineage(List<String> globalIdLineage) {
    this.globalIdLineage = globalIdLineage;
  }

  public Organizer author(Integer author) {
    this.author = author;
    return this;
  }

   /**
   * The organizer author WordPress post ID
   * @return author
  **/
  @ApiModelProperty(value = "The organizer author WordPress post ID")
  public Integer getAuthor() {
    return author;
  }

  public void setAuthor(Integer author) {
    this.author = author;
  }

  public Organizer date(String date) {
    this.date = date;
    return this;
  }

   /**
   * The organizer creation date in the site timezone
   * @return date
  **/
  @ApiModelProperty(value = "The organizer creation date in the site timezone")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Organizer dateUtc(String dateUtc) {
    this.dateUtc = dateUtc;
    return this;
  }

   /**
   * The organizer creation date in UTC time
   * @return dateUtc
  **/
  @ApiModelProperty(value = "The organizer creation date in UTC time")
  public String getDateUtc() {
    return dateUtc;
  }

  public void setDateUtc(String dateUtc) {
    this.dateUtc = dateUtc;
  }

  public Organizer modified(String modified) {
    this.modified = modified;
    return this;
  }

   /**
   * The organizer last modification date in the site timezone
   * @return modified
  **/
  @ApiModelProperty(value = "The organizer last modification date in the site timezone")
  public String getModified() {
    return modified;
  }

  public void setModified(String modified) {
    this.modified = modified;
  }

  public Organizer modifiedUtc(String modifiedUtc) {
    this.modifiedUtc = modifiedUtc;
    return this;
  }

   /**
   * The organizer last modification date in UTC time
   * @return modifiedUtc
  **/
  @ApiModelProperty(value = "The organizer last modification date in UTC time")
  public String getModifiedUtc() {
    return modifiedUtc;
  }

  public void setModifiedUtc(String modifiedUtc) {
    this.modifiedUtc = modifiedUtc;
  }

  public Organizer status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The organizer status
   * @return status
  **/
  @ApiModelProperty(value = "The organizer status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Organizer url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to the organizer page
   * @return url
  **/
  @ApiModelProperty(value = "The URL to the organizer page")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Organizer organizer(String organizer) {
    this.organizer = organizer;
    return this;
  }

   /**
   * The organizer name
   * @return organizer
  **/
  @ApiModelProperty(value = "The organizer name")
  public String getOrganizer() {
    return organizer;
  }

  public void setOrganizer(String organizer) {
    this.organizer = organizer;
  }

  public Organizer description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The organizer long description
   * @return description
  **/
  @ApiModelProperty(value = "The organizer long description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Organizer excerpt(String excerpt) {
    this.excerpt = excerpt;
    return this;
  }

   /**
   * The organizer short description
   * @return excerpt
  **/
  @ApiModelProperty(value = "The organizer short description")
  public String getExcerpt() {
    return excerpt;
  }

  public void setExcerpt(String excerpt) {
    this.excerpt = excerpt;
  }

  public Organizer image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * The event featured image details if set
   * @return image
  **/
  @ApiModelProperty(value = "The event featured image details if set")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Organizer phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * The organizer phone number
   * @return phone
  **/
  @ApiModelProperty(value = "The organizer phone number")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Organizer website(String website) {
    this.website = website;
    return this;
  }

   /**
   * The organizer website
   * @return website
  **/
  @ApiModelProperty(value = "The organizer website")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Organizer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The organizer email address
   * @return email
  **/
  @ApiModelProperty(value = "The organizer email address")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organizer organizer = (Organizer) o;
    return Objects.equals(this.id, organizer.id) &&
        Objects.equals(this.globalId, organizer.globalId) &&
        Objects.equals(this.globalIdLineage, organizer.globalIdLineage) &&
        Objects.equals(this.author, organizer.author) &&
        Objects.equals(this.date, organizer.date) &&
        Objects.equals(this.dateUtc, organizer.dateUtc) &&
        Objects.equals(this.modified, organizer.modified) &&
        Objects.equals(this.modifiedUtc, organizer.modifiedUtc) &&
        Objects.equals(this.status, organizer.status) &&
        Objects.equals(this.url, organizer.url) &&
        Objects.equals(this.organizer, organizer.organizer) &&
        Objects.equals(this.description, organizer.description) &&
        Objects.equals(this.excerpt, organizer.excerpt) &&
        Objects.equals(this.image, organizer.image) &&
        Objects.equals(this.phone, organizer.phone) &&
        Objects.equals(this.website, organizer.website) &&
        Objects.equals(this.email, organizer.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, globalId, globalIdLineage, author, date, dateUtc, modified, modifiedUtc, status, url, organizer, description, excerpt, image, phone, website, email);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organizer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    globalIdLineage: ").append(toIndentedString(globalIdLineage)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateUtc: ").append(toIndentedString(dateUtc)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    modifiedUtc: ").append(toIndentedString(modifiedUtc)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    organizer: ").append(toIndentedString(organizer)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    excerpt: ").append(toIndentedString(excerpt)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

