/*
 * The Events Calendar REST API
 * The Events Calendar REST API allows accessing upcoming events information easily and conveniently.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.soteapi.wordpress.events.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Term
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-11T23:28:38.367+02:00")
@JsonIgnoreProperties (ignoreUnknown = true)
public class Term {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("slug")
  private String slug = null;

  @JsonProperty("taxonomy")
  private String taxonomy = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("parent")
  private Integer parent = null;

  @JsonProperty("count")
  private Integer count = null;

  @JsonProperty("url")
  private String url = null;

  public Term id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The WordPress term ID
   * @return id
  **/
  @ApiModelProperty(value = "The WordPress term ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Term name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The term name
   * @return name
  **/
  @ApiModelProperty(value = "The term name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Term slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * The term slug
   * @return slug
  **/
  @ApiModelProperty(value = "The term slug")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Term taxonomy(String taxonomy) {
    this.taxonomy = taxonomy;
    return this;
  }

   /**
   * The taxonomy the term belongs to
   * @return taxonomy
  **/
  @ApiModelProperty(value = "The taxonomy the term belongs to")
  public String getTaxonomy() {
    return taxonomy;
  }

  public void setTaxonomy(String taxonomy) {
    this.taxonomy = taxonomy;
  }

  public Term description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The term description
   * @return description
  **/
  @ApiModelProperty(value = "The term description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Term parent(Integer parent) {
    this.parent = parent;
    return this;
  }

   /**
   * The term parent term if any
   * @return parent
  **/
  @ApiModelProperty(value = "The term parent term if any")
  public Integer getParent() {
    return parent;
  }

  public void setParent(Integer parent) {
    this.parent = parent;
  }

  public Term count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * The number of posts associated with the term
   * @return count
  **/
  @ApiModelProperty(value = "The number of posts associated with the term")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public Term url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to the term archive page
   * @return url
  **/
  @ApiModelProperty(value = "The URL to the term archive page")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Term term = (Term) o;
    return Objects.equals(this.id, term.id) &&
        Objects.equals(this.name, term.name) &&
        Objects.equals(this.slug, term.slug) &&
        Objects.equals(this.taxonomy, term.taxonomy) &&
        Objects.equals(this.description, term.description) &&
        Objects.equals(this.parent, term.parent) &&
        Objects.equals(this.count, term.count) &&
        Objects.equals(this.url, term.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, slug, taxonomy, description, parent, count, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Term {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    taxonomy: ").append(toIndentedString(taxonomy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

