/*
 * The Events Calendar REST API
 * The Events Calendar REST API allows accessing upcoming events information easily and conveniently.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.soteapi.wordpress.events.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Venue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-11T23:28:38.367+02:00")
public class Venue {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("global_id")
  private String globalId = null;

  @JsonProperty("global_id_lineage")
  private List<String> globalIdLineage = null;

  @JsonProperty("author")
  private Integer author = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("date_utc")
  private String dateUtc = null;

  @JsonProperty("modified")
  private String modified = null;

  @JsonProperty("modified_utc")
  private String modifiedUtc = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("url")
  private String url = null;

  @JsonProperty("venue")
  private String venue = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("excerpt")
  private String excerpt = null;

  @JsonProperty("image")
  private Image image = null;

  @JsonProperty("show_map")
  private Boolean showMap = null;

  @JsonProperty("show_map_link")
  private Boolean showMapLink = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("province")
  private String province = null;

  @JsonProperty("state")
  private String state = null;

  @JsonProperty("zip")
  private String zip = null;

  @JsonProperty("phone")
  private String phone = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("stateprovince")
  private String stateprovince = null;

  @JsonProperty("geo_lat")
  private Double geoLat = null;

  @JsonProperty("geo_lng")
  private Double geoLng = null;

  public Venue id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * The venue WordPress post ID
   * @return id
  **/
  @ApiModelProperty(value = "The venue WordPress post ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Venue globalId(String globalId) {
    this.globalId = globalId;
    return this;
  }

   /**
   * The venue ID used to globally identify in Event Aggregator
   * @return globalId
  **/
  @ApiModelProperty(value = "The venue ID used to globally identify in Event Aggregator")
  public String getGlobalId() {
    return globalId;
  }

  public void setGlobalId(String globalId) {
    this.globalId = globalId;
  }

  public Venue globalIdLineage(List<String> globalIdLineage) {
    this.globalIdLineage = globalIdLineage;
    return this;
  }

  public Venue addGlobalIdLineageItem(String globalIdLineageItem) {
    if (this.globalIdLineage == null) {
      this.globalIdLineage = new ArrayList<String>();
    }
    this.globalIdLineage.add(globalIdLineageItem);
    return this;
  }

   /**
   * An Array containing the lineage of where this organizer comes from, this should not change after the organizer is created.
   * @return globalIdLineage
  **/
  @ApiModelProperty(value = "An Array containing the lineage of where this organizer comes from, this should not change after the organizer is created.")
  public List<String> getGlobalIdLineage() {
    return globalIdLineage;
  }

  public void setGlobalIdLineage(List<String> globalIdLineage) {
    this.globalIdLineage = globalIdLineage;
  }

  public Venue author(Integer author) {
    this.author = author;
    return this;
  }

   /**
   * The venue author WordPress post ID
   * @return author
  **/
  @ApiModelProperty(value = "The venue author WordPress post ID")
  public Integer getAuthor() {
    return author;
  }

  public void setAuthor(Integer author) {
    this.author = author;
  }

  public Venue date(String date) {
    this.date = date;
    return this;
  }

   /**
   * The venue creation date in the site timezone
   * @return date
  **/
  @ApiModelProperty(value = "The venue creation date in the site timezone")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Venue dateUtc(String dateUtc) {
    this.dateUtc = dateUtc;
    return this;
  }

   /**
   * The venue creation date in UTC time
   * @return dateUtc
  **/
  @ApiModelProperty(value = "The venue creation date in UTC time")
  public String getDateUtc() {
    return dateUtc;
  }

  public void setDateUtc(String dateUtc) {
    this.dateUtc = dateUtc;
  }

  public Venue modified(String modified) {
    this.modified = modified;
    return this;
  }

   /**
   * The venue last modification date in the site timezone
   * @return modified
  **/
  @ApiModelProperty(value = "The venue last modification date in the site timezone")
  public String getModified() {
    return modified;
  }

  public void setModified(String modified) {
    this.modified = modified;
  }

  public Venue modifiedUtc(String modifiedUtc) {
    this.modifiedUtc = modifiedUtc;
    return this;
  }

   /**
   * The venue last modification date in UTC time
   * @return modifiedUtc
  **/
  @ApiModelProperty(value = "The venue last modification date in UTC time")
  public String getModifiedUtc() {
    return modifiedUtc;
  }

  public void setModifiedUtc(String modifiedUtc) {
    this.modifiedUtc = modifiedUtc;
  }

  public Venue status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The venue status
   * @return status
  **/
  @ApiModelProperty(value = "The venue status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Venue url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The URL to the venue page
   * @return url
  **/
  @ApiModelProperty(value = "The URL to the venue page")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Venue venue(String venue) {
    this.venue = venue;
    return this;
  }

   /**
   * The venue name
   * @return venue
  **/
  @ApiModelProperty(value = "The venue name")
  public String getVenue() {
    return venue;
  }

  public void setVenue(String venue) {
    this.venue = venue;
  }

  public Venue description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The venue long description
   * @return description
  **/
  @ApiModelProperty(value = "The venue long description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Venue excerpt(String excerpt) {
    this.excerpt = excerpt;
    return this;
  }

   /**
   * The venue short description
   * @return excerpt
  **/
  @ApiModelProperty(value = "The venue short description")
  public String getExcerpt() {
    return excerpt;
  }

  public void setExcerpt(String excerpt) {
    this.excerpt = excerpt;
  }

  public Venue image(Image image) {
    this.image = image;
    return this;
  }

   /**
   * The event featured image details if set
   * @return image
  **/
  @ApiModelProperty(value = "The event featured image details if set")
  public Image getImage() {
    return image;
  }

  public void setImage(Image image) {
    this.image = image;
  }

  public Venue showMap(Boolean showMap) {
    this.showMap = showMap;
    return this;
  }

   /**
   * Whether the map should be shown for the venue or not
   * @return showMap
  **/
  @ApiModelProperty(value = "Whether the map should be shown for the venue or not")
  public Boolean isShowMap() {
    return showMap;
  }

  public void setShowMap(Boolean showMap) {
    this.showMap = showMap;
  }

  public Venue showMapLink(Boolean showMapLink) {
    this.showMapLink = showMapLink;
    return this;
  }

   /**
   * Whether the map link should be shown for the venue or not
   * @return showMapLink
  **/
  @ApiModelProperty(value = "Whether the map link should be shown for the venue or not")
  public Boolean isShowMapLink() {
    return showMapLink;
  }

  public void setShowMapLink(Boolean showMapLink) {
    this.showMapLink = showMapLink;
  }

  public Venue address(String address) {
    this.address = address;
    return this;
  }

   /**
   * The venue address
   * @return address
  **/
  @ApiModelProperty(value = "The venue address")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public Venue city(String city) {
    this.city = city;
    return this;
  }

   /**
   * The venue city
   * @return city
  **/
  @ApiModelProperty(value = "The venue city")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public Venue country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The venue country
   * @return country
  **/
  @ApiModelProperty(value = "The venue country")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public Venue province(String province) {
    this.province = province;
    return this;
  }

   /**
   * The venue province
   * @return province
  **/
  @ApiModelProperty(value = "The venue province")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public Venue state(String state) {
    this.state = state;
    return this;
  }

   /**
   * The venue state
   * @return state
  **/
  @ApiModelProperty(value = "The venue state")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public Venue zip(String zip) {
    this.zip = zip;
    return this;
  }

   /**
   * The venue ZIP code
   * @return zip
  **/
  @ApiModelProperty(value = "The venue ZIP code")
  public String getZip() {
    return zip;
  }

  public void setZip(String zip) {
    this.zip = zip;
  }

  public Venue phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * The venue phone number
   * @return phone
  **/
  @ApiModelProperty(value = "The venue phone number")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public Venue website(String website) {
    this.website = website;
    return this;
  }

   /**
   * The venue website URL
   * @return website
  **/
  @ApiModelProperty(value = "The venue website URL")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Venue stateprovince(String stateprovince) {
    this.stateprovince = stateprovince;
    return this;
  }

   /**
   * The venue state or province
   * @return stateprovince
  **/
  @ApiModelProperty(value = "The venue state or province")
  public String getStateprovince() {
    return stateprovince;
  }

  public void setStateprovince(String stateprovince) {
    this.stateprovince = stateprovince;
  }

  public Venue geoLat(Double geoLat) {
    this.geoLat = geoLat;
    return this;
  }

   /**
   * The venue geo latitude
   * @return geoLat
  **/
  @ApiModelProperty(value = "The venue geo latitude")
  public Double getGeoLat() {
    return geoLat;
  }

  public void setGeoLat(Double geoLat) {
    this.geoLat = geoLat;
  }

  public Venue geoLng(Double geoLng) {
    this.geoLng = geoLng;
    return this;
  }

   /**
   * The venue geo longitude
   * @return geoLng
  **/
  @ApiModelProperty(value = "The venue geo longitude")
  public Double getGeoLng() {
    return geoLng;
  }

  public void setGeoLng(Double geoLng) {
    this.geoLng = geoLng;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Venue venue = (Venue) o;
    return Objects.equals(this.id, venue.id) &&
        Objects.equals(this.globalId, venue.globalId) &&
        Objects.equals(this.globalIdLineage, venue.globalIdLineage) &&
        Objects.equals(this.author, venue.author) &&
        Objects.equals(this.date, venue.date) &&
        Objects.equals(this.dateUtc, venue.dateUtc) &&
        Objects.equals(this.modified, venue.modified) &&
        Objects.equals(this.modifiedUtc, venue.modifiedUtc) &&
        Objects.equals(this.status, venue.status) &&
        Objects.equals(this.url, venue.url) &&
        Objects.equals(this.venue, venue.venue) &&
        Objects.equals(this.description, venue.description) &&
        Objects.equals(this.excerpt, venue.excerpt) &&
        Objects.equals(this.image, venue.image) &&
        Objects.equals(this.showMap, venue.showMap) &&
        Objects.equals(this.showMapLink, venue.showMapLink) &&
        Objects.equals(this.address, venue.address) &&
        Objects.equals(this.city, venue.city) &&
        Objects.equals(this.country, venue.country) &&
        Objects.equals(this.province, venue.province) &&
        Objects.equals(this.state, venue.state) &&
        Objects.equals(this.zip, venue.zip) &&
        Objects.equals(this.phone, venue.phone) &&
        Objects.equals(this.website, venue.website) &&
        Objects.equals(this.stateprovince, venue.stateprovince) &&
        Objects.equals(this.geoLat, venue.geoLat) &&
        Objects.equals(this.geoLng, venue.geoLng);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, globalId, globalIdLineage, author, date, dateUtc, modified, modifiedUtc, status, url, venue, description, excerpt, image, showMap, showMapLink, address, city, country, province, state, zip, phone, website, stateprovince, geoLat, geoLng);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Venue {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    globalIdLineage: ").append(toIndentedString(globalIdLineage)).append("\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateUtc: ").append(toIndentedString(dateUtc)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    modifiedUtc: ").append(toIndentedString(modifiedUtc)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    venue: ").append(toIndentedString(venue)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    excerpt: ").append(toIndentedString(excerpt)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    showMap: ").append(toIndentedString(showMap)).append("\n");
    sb.append("    showMapLink: ").append(toIndentedString(showMapLink)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    stateprovince: ").append(toIndentedString(stateprovince)).append("\n");
    sb.append("    geoLat: ").append(toIndentedString(geoLat)).append("\n");
    sb.append("    geoLng: ").append(toIndentedString(geoLng)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

